name: Run tests

on:
  push:
  pull_request:
    branches:
      - main
jobs:
  run_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - uses: actions/setup-python@v1
        with:
          python-version: '3.7'
      - name: Run tests
        run: python -m unittest -v test_main
