name: Run tests

on:
  push:
    branches:
      - main

jobs:
  run_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - uses: actions/setup-python@v1
        with:
          python-version: '3.7'
      - name: Run tests
        run: python -m unittest -v test_main
      - name: Upload Unit Test Results
              uses: actions/upload-artifact@v2
              with:
                name: Unit Test Results
                path: pytest.xml
                
  publish-test-results:
    name: Publish Unit Tests Results
    needs: build-and-test
    runs-on: ubuntu-latest
    if: always()

    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v2
        with:
          path: artifacts

      - name: Publish Unit Test Results
        uses: EnricoMi/publish-unit-test-result-action@v1
        with:
          files: artifacts/**/*.xml
